[package]
name = "rotary_alarm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruduino = "0.3.2"
[profile.release]
panic = "abort"
lto = true
